services:
  postgres:
    image: postgres:16
    container_name: flight_postgres
    restart: always
    environment:
      POSTGRES_USER: flight
      POSTGRES_PASSWORD: flightpass
      POSTGRES_DB: flight_deals
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: flight_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
